-- MySQL Script generated by MySQL Workbench
-- 11/16/17 09:29:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema konference
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `konference` ;

-- -----------------------------------------------------
-- Schema konference
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `konference` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `konference` ;

-- -----------------------------------------------------
-- Table `Uzivatel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Uzivatel` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Uzivatel` (
  `id_uzivatel` INT NOT NULL AUTO_INCREMENT,
  `uzivatel_jmeno` VARCHAR(45) NULL,
  `uzivatel_heslo` VARCHAR(45) NULL,
  `uzivatel_nazev` VARCHAR(45) NULL,
  `uzivatel_email` VARCHAR(45) NULL,
  `uzivatel_typ` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id_uzivatel`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_uzivatel_UNIQUE` ON `Uzivatel` (`id_uzivatel` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Statistika`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Statistika` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Statistika` (
  `id_statistika` INT NOT NULL AUTO_INCREMENT,
  `statistika_id_nejnovejsi_uzivatel` INT NOT NULL,
  `statistika_pocet_uzivatelu` INT NOT NULL,
  `statistika_pocet_prispevku` INT NOT NULL,
  PRIMARY KEY (`id_statistika`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_statistika_UNIQUE` ON `Statistika` (`id_statistika` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Forum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Forum` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Forum` (
  `id_forum` INT NOT NULL AUTO_INCREMENT,
  `forum_id_administrator` INT NOT NULL,
  `forum_id_statistika` INT NOT NULL,
  `forum_jmeno` VARCHAR(45) NULL,
  `forum_popis` VARCHAR(45) NULL,
  PRIMARY KEY (`id_forum`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_forum_UNIQUE` ON `Forum` (`id_forum` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Prispevek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Prispevek` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Prispevek` (
  `id_prispevek` INT NOT NULL AUTO_INCREMENT,
  `prispevek_id_autor` INT NOT NULL,
  `prispevek_id_forum` INT NOT NULL,
  `prispevek_id_recenzent` INT NOT NULL,
  `prispevek_id_rodicPrispevek` INT NULL,
  `prispevek_nazev` VARCHAR(45) NULL,
  `prispevek_text` VARCHAR(250) NULL,
  `prispevek_soubor` MEDIUMBLOB NULL,
  PRIMARY KEY (`id_prispevek`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_prispevek_UNIQUE` ON `Prispevek` (`id_prispevek` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PosudekCiselnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PosudekCiselnik` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PosudekCiselnik` (
  `id_posudek_ciselnik` INT NOT NULL AUTO_INCREMENT,
  `posudek_ciselnik_typ` VARCHAR(1) NULL,
  `posudek_ciselnik_typ_popis` VARCHAR(45) NULL,
  PRIMARY KEY (`id_posudek_ciselnik`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Posudek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Posudek` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Posudek` (
  `id_posudek` INT NOT NULL AUTO_INCREMENT,
  `posudek_id_posudek_ciselnik_orig` INT NOT NULL,
  `posudek_id_posudek_ciselnik_tema` INT NOT NULL,
  `posudek_id_posudek_cislenik_doporuceni` INT NOT NULL,
  `posudek_id_recenzent` INT NOT NULL,
  `posudek_id_prispevek` INT NOT NULL,
  `posudek_poznamka` VARCHAR(250) NULL,
  PRIMARY KEY (`id_posudek`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
